#! /usr/bin/python
"""
.. module:: batchFarmServices
   :platform: Unix, Windows, OSX
   :synopsis: Utilities for doing PWA with the Jlab batch system.

.. moduleauthor:: Joshua Pond <jpond@jlab.org>


""" 

import os, glob, sys 
from subprocess import Popen 

nfile = sys.argv[2]+".bamp"
oI = sys.argv[1]

if os.path.isdir(os.path.join(os.getcwd().strip("GUI"),"fitting"):
    for d in os.listdir(os.path.join(os.getcwd().strip("GUI"),"fitting")):
        if "_MeV" in d:
            for m in ("mc","data"):
                if m == "data":
                    if oI == "o":
                        cmd = 'mv '+os.path.join(os.getcwd().strip("GUI"),"fitting",str(d),str(m),nfile)+" "+os.path.join(os.getcwd().strip("GUI"),"fitting","overflow",str(d),str(m)+str(nfile))
                    if oI == "i":
                        cmd = 'mv '+os.path.join(os.getcwd().strip("GUI"),"fitting","overflow",str(d),str(m)+str(nfile))+" "+os.path.join(os.getcwd().strip("GUI"),"fitting",str(d),str(m),nfile)
                    proc = Popen(cmd,shell = True,executable = os.environ.get('SHELL', '/bin/tcsh'),env = os.environ)
                    proc.wait()
                if m == "mc":
                    for a in ("acc","raw"):
                        if oI == "o":
                            cmd = 'mv '+os.path.join(os.getcwd().strip("GUI"),"fitting",str(d),str(m),str(a),nfile)+" "+os.path.join(os.getcwd().strip("GUI"),"fitting","overflow",str(d),str(a)+str(m)+str(nfile))
                        if oI == "i":
                            cmd = 'mv '+os.path.join(os.getcwd().strip("GUI"),"fitting","overflow",str(d),str(a)+str(m)+str(nfile))+" "+os.path.join(os.getcwd().strip("GUI"),"fitting",str(d),str(m),str(a),nfile)
                        proc = Popen(cmd,shell = True,executable = os.environ.get('SHELL', '/bin/tcsh'),env = os.environ)
                        proc.wait()                    
            sys.stdout.write(d.rstrip("_MeV")+"\r")
            sys.stdout.flush()
    print "DONE    "
elif os.path.isdir(os.path.join(os.getcwd().strip("GUI"),"simulation"):
    for d in os.listdir(os.path.join(os.getcwd().strip("GUI"),"simulation")):
        if "_MeV" in d:
            if oI == "o":
                cmd = 'mv '+os.path.join(os.getcwd().strip("GUI"),"simulation",str(d),"flat",nfile)+" "+os.path.join(os.getcwd().strip("GUI"),"simulation","overflow",str(d),"flat"+str(nfile))
            if oI == "i":
                cmd = 'mv '+os.path.join(os.getcwd().strip("GUI"),"simulation","overflow",str(d),"flat"+str(nfile))+" "+os.path.join(os.getcwd().strip("GUI"),"simulation",str(d),"flat",nfile)
            proc = Popen(cmd,shell = True,executable = os.environ.get('SHELL', '/bin/tcsh'),env = os.environ)
            proc.wait()                                    
            sys.stdout.write(d.rstrip("_MeV")+"\r")
            sys.stdout.flush()
    print "DONE    "
