sudo: false
dist: xenial
language: python
cache: pip
python:
  - "3.7"
  - "3.8-dev"
matrix:
  allow_failures:
    - python: "3.8-dev"
addons:
  apt:
    packages:
      - "build-essential"
      - "gfortran"
      - "libatlas-base-dev"
      - "libopenblas-dev"
      - "liblapack-dev"
      - "python-dev"
      - "cython"
before_install:
  - "pip install --upgrade pip setuptools wheel"
  - "pip install --upgrade numpy scipy"
  - "pip install --upgrade iminuit nestle ruamel.yaml tabulate appdirs"
  - "pip install --upgrade fuzzywuzzy python-Levenshtein"
  - "pip install --upgrade coveralls coverage"
  - "pip install --upgrade pytest pytest-runner pytest-cov"
install:
  - "pip install --upgrade -e ."
script: "pytest --cov=PyPWA tests --cov-report="
after_success:
  - coveralls
notifications:
  emails:
    on_success: change
    on_failure: change
