name: PyPWA
channels:
  - defaults
dependencies:
  - python                  # Current latest Python
  - conda-forge::emcee>3.0  # Optional dependency for MCMC
  - jupyterlab              # Jupyter and Jupyter Lab support
  - ipython                 # Quick CLI python interface
  - tensorflow              # Machine Learning
  - pytorch                 # Machine Learning using Torch
  - tabulate                # Better iMinuit tables
  - scipy                   # Scientific Python
  - matplotlib              # Graphing
  - seaborn                 # Optional; Nicer Graphs
  - ipympl                  # 3D Graphs
  - tqdm                    # Progress Bars
  - iminuit
  - numpy
  - pandas
  - numexpr
  - pytest

