name: PyPWA
channels:
  - defaults
dependencies:
  - python=3.9              # Current latest Python
  - markjonestx::pypwa      # PyPWA
  - conda-forge::emcee>3.0  # Optional dependency for MCMC
  - conda-forge::nestle     # Multinest optimization
  - jupyterlab              # Jupyter and Jupyter Lab support
  - ipython                 # Quick CLI python interface
  - tensorflow              # Machine Learning
  - pytorch                 # Machine Learning using Torch
  - scikit-learn            # Machine Learning through Scikit
  - tabulate                # Better iMinuit tables
  - scipy                   # Scientific Python
  - matplotlib              # Graphing
  - seaborn                 # Optional; Nicer Graphs
  - ipympl                  # 3D Graphs
  - tqdm                    # Progress Bars

