#! /u/apps/anaconda/anaconda-2.0.1/bin/python2 
import os
import numpy,sys
import subprocess as sp
from subprocess import Popen

indir = os.path.split(os.path.split(os.getcwd())[0])[0]
print "Top Directory: ",indir
if not os.path.isfile(os.path.join("Control_List.npy")):
    sp.call("pwa_controls")
Control = numpy.load(os.path.join("Control_List.npy"))  
print("Creating directory structure for PyPWA fitting")
tdirs = ("fitting","GUI","keyfiles","scripts","simulation")
for i in tdirs:
    directoryBuffer=os.path.join(indir,str(i))
    os.makedirs(directoryBuffer)
    if i != tdirs[-1]:
        sys.stdout.write("Writing Directories"+"."*(tdirs.index(i)+1)+"\r")
        sys.stdout.flush()
    elif i == tdirs[-1]:
        sys.stdout.write("Writing Directories"+"."*(tdirs.index(i)+1)+"\r\n")
        sys.stdout.flush()
    if i == "fitting":
        for d in ("overflow","results"):
            directoryBuffer=os.path.join(indir,"fitting",str(d))
            os.makedirs(directoryBuffer)  
    if i == "GUI":
        directoryBuffer=os.path.join(indir,"GUI","plotLists")
        os.makedirs(directoryBuffer)          
    if i == "scripts":
        directoryBuffer=os.path.join(indir,"scripts","submitions")
        os.makedirs(directoryBuffer)        
progs = ("fnGenerator.py","generateAlphas.py","GUI_alpha_main.py",
"GUI_gamp_main.py","GUI_subPyNormInt.py","likelihoodTest.py","mvBAMP_GUI",
"run_normintFARM.py","subLikelihood","subWalkNTrue","walkingNTrue.py","dirSplitter.py","MCdir.py")
for s in progs:
    cmd = 'cp '+os.path.join(os.getcwd(),str(s))+" "+os.path.join(indir,"scripts")
    proc = Popen(cmd,shell = True,executable = os.environ.get('SHELL', '/bin/tcsh'),env = os.environ)
    proc.wait()
    if s != progs[-1]:
        sys.stdout.write("Filling scripts"+"."*(progs.index(s)+1)+"\r")
        sys.stdout.flush()
    elif s == progs[-1]:
        sys.stdout.write("Filling scripts"+"."*(progs.index(s)+1)+"\r\n")
        sys.stdout.flush()
guis = ("graphicPlot","pwa_controls","PWA_GUI","Control_List.npy")
for g in guis:
    cmd = 'cp '+os.path.join(os.getcwd(),str(g))+" "+os.path.join(indir,"GUI")
    proc = Popen(cmd,shell = True,executable = os.environ.get('SHELL', '/bin/tcsh'),env = os.environ)
    proc.wait()
    if g != guis[-1]:    
        sys.stdout.write("Filling GUI"+"."*(guis.index(g)+1)+"\r")
        sys.stdout.flush()
    elif g == guis[-1]:
        sys.stdout.write("Filling GUI"+"."*(guis.index(g)+1)+"\r\n")
        sys.stdout.flush()        
cmd = indir+"/scripts/dirSplitter.py "+os.path.join(indir,"fitting")+" "+os.path.join(indir,"fitting","results")+" "+os.path.join(indir,"fitting","overflow")
cmd1 = indir+"/scripts/MCdir.py"
for c in (cmd,cmd1):
    procx = Popen(c,shell = True,executable = os.environ.get('SHELL', '/bin/tcsh'),env = os.environ)
    procx.wait()
print "Welcome to PyPWA!\nYou are now ready to start Partial Wave Analysis!"
